#define SEMICOLON                       1
#define NIL                             2
#define TRUE                            3
#define FALSE                           4
#define NUMBER                          5
#define STRING                          6
#define ELLIPSES                        7
#define NOT                             8
#define SHARP                           9
#define OR                             10
#define AND                            11
#define LT                             12
#define LEQT                           13
#define GT                             14
#define GEQT                           15
#define EQUAL                          16
#define NOT_EQUAL                      17
#define CONCAT                         18
#define PLUS                           19
#define MINUS                          20
#define MULT                           21
#define DIV                            22
#define MOD                            23
#define RAISE                          24
