
GSH_SF_D_MODE(airy, Ai)
GSH_SF_ZERO(airy, Ai)

GSH_SF_D_MODE(airy, Bi)
GSH_SF_ZERO(airy, Bi)

GSH_SF_D(bessel, J0)
GSH_SF_D(bessel, J1)
GSH_SF_ID(bessel, Jn)
GSH_SF_D(bessel, Y0)
GSH_SF_D(bessel, Y1)
GSH_SF_ID(bessel, Yn)
GSH_SF_D(bessel, I0)
GSH_SF_D(bessel, I1)
GSH_SF_ID(bessel, In)
GSH_SF_D(bessel, K0)
GSH_SF_D(bessel, K1)
GSH_SF_ID(bessel, Kn)
GSH_SF_ZERO(bessel, J0)
GSH_SF_ZERO(bessel, J1)
GSH_SF_ZERO_D(bessel, Jnu)

GSH_SF_D_SIMPLE(erf)

GSH_SF_D(expint, E1)
GSH_SF_D(expint, E2)
GSH_SF_ID(expint, En)
GSH_SF_D(expint, Ei)
GSH_SF_D(expint, 3)

GSH_SF_D_SIMPLE(Shi)
GSH_SF_D_SIMPLE(Chi)
GSH_SF_D_SIMPLE(Si)
GSH_SF_D_SIMPLE(Ci)
GSH_SF_D_SIMPLE(atanint)

GSH_SF_U_SIMPLE(fact)
GSH_SF_U_SIMPLE(doublefact)
GSH_SF_U_SIMPLE(lnfact)
GSH_SF_U_SIMPLE(lndoublefact)
GSH_SF_UU_SIMPLE(choose)
GSH_SF_UU_SIMPLE(lnchoose)

GSH_SF_D_SIMPLE(gamma)
GSH_SF_D_SIMPLE(lngamma)
GSH_SF_DD_SIMPLE(beta)
GSH_SF_DD_SIMPLE(lnbeta)

GSH_SF_D(legendre, P1)
GSH_SF_D(legendre, P2)
GSH_SF_D(legendre, P3)
GSH_SF_ID(legendre, Pl)
GSH_SF_D(legendre, Q0)
GSH_SF_D(legendre, Q1)
GSH_SF_ID(legendre, Ql)

GSH_SF_DD(hyperg, 0F1)
GSH_SF_IID_SUFFIX(hyperg, 1F1, int)
GSH_SF_DDD(hyperg, 1F1)
