##############################################################################
# See file src/Makefile for build options
#
# Suitable for POSIX platforms (Linux, *BSD, OSX etc.)
# Note: the configurable options are in makeconfig
# 
# Copyright (C) 2009-2010 Francesco Abbate. See Copyright Notice in gsl-shell.c
##############################################################################

all:
	$(MAKE) -C src

clean:
	$(MAKE) -C src clean

# list targets that do not create files (but not all makes understand .PHONY)
.PHONY: all clean
