-- tests for module randist
use'randist'
local t = {}

local x=0.1
local sigma=1
local mu=1
local nu=9
local a=3
local nu1=2
local nu2=4
local b=2
local zeta=1
local p=0.4
local n=8

t.gaussian_pdf = function() return gaussian_pdf(x, sigma) end
t.gaussian_P = function() return gaussian_P(x, sigma) end
t.gaussian_Q = function() return gaussian_Q(x, sigma) end
t.gaussian_Pinv = function() return gaussian_Pinv(x, sigma) end
t.gaussian_Qinv = function() return gaussian_Qinv(x, sigma) end
t.exponential_pdf = function() return exponential_pdf(x, mu) end
t.exponential_P = function() return exponential_P(x, mu) end
t.exponential_Q = function() return exponential_Q(x, mu) end
t.exponential_Pinv = function() return exponential_Pinv(x, mu) end
t.exponential_Qinv = function() return exponential_Qinv(x, mu) end
t.chisq_pdf = function() return chisq_pdf(x, nu) end
t.chisq_P = function() return chisq_P(x, nu) end
t.chisq_Q = function() return chisq_Q(x, nu) end
t.chisq_Pinv = function() return chisq_Pinv(x, nu) end
t.chisq_Qinv = function() return chisq_Qinv(x, nu) end
t.laplace_pdf = function() return laplace_pdf(x, a) end
t.laplace_P = function() return laplace_P(x, a) end
t.laplace_Q = function() return laplace_Q(x, a) end
t.laplace_Pinv = function() return laplace_Pinv(x, a) end
t.laplace_Qinv = function() return laplace_Qinv(x, a) end
t.tdist_pdf = function() return tdist_pdf(x, nu) end
t.tdist_P = function() return tdist_P(x, nu) end
t.tdist_Q = function() return tdist_Q(x, nu) end
t.tdist_Pinv = function() return tdist_Pinv(x, nu) end
t.tdist_Qinv = function() return tdist_Qinv(x, nu) end
t.cauchy_pdf = function() return cauchy_pdf(x, a) end
t.cauchy_P = function() return cauchy_P(x, a) end
t.cauchy_Q = function() return cauchy_Q(x, a) end
t.cauchy_Pinv = function() return cauchy_Pinv(x, a) end
t.cauchy_Qinv = function() return cauchy_Qinv(x, a) end
t.rayleigh_pdf = function() return rayleigh_pdf(x, sigma) end
t.rayleigh_P = function() return rayleigh_P(x, sigma) end
t.rayleigh_Q = function() return rayleigh_Q(x, sigma) end
t.rayleigh_Pinv = function() return rayleigh_Pinv(x, sigma) end
t.rayleigh_Qinv = function() return rayleigh_Qinv(x, sigma) end
t.fdist_pdf = function() return fdist_pdf(x, nu1, nu2) end
t.fdist_P = function() return fdist_P(x, nu1, nu2) end
t.fdist_Q = function() return fdist_Q(x, nu1, nu2) end
t.fdist_Pinv = function() return fdist_Pinv(x, nu1, nu2) end
t.fdist_Qinv = function() return fdist_Qinv(x, nu1, nu2) end
t.gamma_pdf = function() return gamma_pdf(x, a, b) end
t.gamma_P = function() return gamma_P(x, a, b) end
t.gamma_Q = function() return gamma_Q(x, a, b) end
t.gamma_Pinv = function() return gamma_Pinv(x, a, b) end
t.gamma_Qinv = function() return gamma_Qinv(x, a, b) end
t.beta_pdf = function() return beta_pdf(x, a, b) end
t.beta_P = function() return beta_P(x, a, b) end
t.beta_Q = function() return beta_Q(x, a, b) end
t.beta_Pinv = function() return beta_Pinv(x, a, b) end
t.beta_Qinv = function() return beta_Qinv(x, a, b) end
t.gaussian_tail_pdf = function() return gaussian_tail_pdf(5, a, sigma) end
t.exppow_pdf = function() return exppow_pdf(x, a, b) end
t.exppow_P = function() return exppow_P(x, a, b) end
t.exppow_Q = function() return exppow_Q(x, a, b) end
t.lognormal_pdf = function() return lognormal_pdf(x, zeta, sigma) end
t.lognormal_P = function() return lognormal_P(x, zeta, sigma) end
t.lognormal_Q = function() return lognormal_Q(x, zeta, sigma) end
t.lognormal_Pinv = function() return lognormal_Pinv(x, zeta, sigma) end
t.lognormal_Qinv = function() return lognormal_Qinv(x, zeta, sigma) end
t.binomial_pdf = function() return binomial_pdf(x, p, n) end
t.binomial_P = function() return binomial_P(x, p, n) end
t.binomial_Q = function() return binomial_Q(x, p, n) end
t.poisson_pdf = function() return poisson_pdf(x, mu) end
t.poisson_P = function() return poisson_P(x, mu) end
t.poisson_Q = function() return poisson_Q(x, mu) end
return t
